### PR TITLE
Fix the return order of batched requests

### PR DESCRIPTION
**Pull request by IMax153**
## Type

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related

- Related Issue #
- Closes #

### CODE REVIEW

**Comment by mikearnaldi** [comment]
I don't think I understand the problem and by consequence the solution, would you mind writing a test?

**Comment by mikearnaldi** [comment]
> While it works and looks good to me, I'm not sure why the behaviour changed after Mike's request refactor.
> 
> I'll defer to @mikearnaldi to review for this one :)

I didn't touch that function

**Comment by IMax153** [comment]
> > While it works and looks good to me, I'm not sure why the behaviour changed after Mike's request refactor.
> > I'll defer to @mikearnaldi to review for this one :)
> 
> I didn't touch that function

I was pretty convinced this was my error in the original port :) We just probably never noticed the issue before.

**Comment by IMax153** [comment]
The issue basically was - if you send a set of batched requests that were received as follows:

```
Request 1 -> Request 2 -> Request 3
```

the results were being returned as:

```
Result 3 -> Result 2 -> Result 1
```

We tracked down the inadvertent reversal of results to this method which was combining results in reverse order instead of the correct order.

I'll write a test in a separate PR - apologies for merging before seeing your messages.

**Pull request merged**
