### PR TITLE
Don't log an empty message

### PR DESCRIPTION
**Pull request by thewilkybarkid**
## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related

- Related Issue #
- Closes #

### CODE REVIEW

**Comment by tim-smart** [comment]
The empty message was intentional, as all the information is in the annotations. Was it breaking something for you?

**Comment by thewilkybarkid** [comment]
It's not breaking anything, it was just a little harder when eyeballing a stream of log messages. (Though this was the only case where the message was empty, so easier once I worked that out. 🙃)

**Comment by mikearnaldi** [comment]
> The empty message was intentional, as all the information is in the annotations. Was it breaking something for you?

Any reason why a log message would be bad?

**Comment by tim-smart** [comment]
Not bad, but my only nit pick is that it makes the stream of logs quite repetitive, as the message adds no value.

**Comment by mikearnaldi** [comment]
Are we logging purely annotations?

**Pull request merged**
