### PR TITLE
Introduce Effect.andThen

### PR DESCRIPTION
**Pull request by mikearnaldi**

### CODE REVIEW

**Review by IMax153 — APPROVED** [review]
I think this is a good addition 👍

**Comment by gcanti** [comment]
I like it. 

Do we also want to add `andThen` to all the other data types implementing `flatMap`?

**Comment by mikearnaldi** [comment]
Seems like a good choice, I am thinking of we can do something to
consolidate tap, like a discard option to andThen

**Comment by mikearnaldi** [comment]
Would it be nuts to add auto-flattening of Effect so that andThen "replaces" map too?

**Comment by IMax153** [comment]
> Would it be nuts to add auto-flattening of Effect so that andThen "replaces" map too?

I kind of really like this idea honestly - then we only have to teach users one thing.

**Comment by mikearnaldi** [comment]
Given we are committing crimes, I've also added auto-flattening to `tap` based on @schickling suggestion and given that some folks are expecting sync functions to be valid. Let me know your view, I am not 100% sure but think it's worth a try

**Comment by tim-smart** [comment]
Auto-flattening Promise with Effect.promise? Too far?

**Comment by mikearnaldi** [comment]
Maybe kind of unsure though it would either introduce an unknown error or
be a defect

**Comment by tim-smart** [comment]
I think if we did promises we would have to introduce a built in error type to wrap rejections.

**Pull request merged**
