### PR TITLE
add Effect.scopedAsDisposable, for integrating Scope with the `using` keyword

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by mikearnaldi** [comment]
maybe just `Effect.disposable` ?

**Comment by mikearnaldi** [comment]
Ah but it doesn't wait for cleanup to complete, it uses runFork so this won't work as it would leak resources

**Comment by mikearnaldi** [comment]
wondering if there is a way to let this "yield" from the dispose

**Comment by tim-smart** [comment]
> wondering if there is a way to let this "yield" from the dispose

You can only have async finalizers if you use async / await unfortunately.

**Pull request closed without merging**
