### PR TITLE
`Cache`, `ScopedCache` swap type parameters

### PR DESCRIPTION
**Pull request by KhraksMamtsov**
## Type

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

`Cache<Key, Error, Value>` has been changed to `Cache<Key, Value, Error = never>`.
`ScopedCache<Key, Error, Value>` has been changed to `ScopedCache<Key, Value, Error = never>`.
`Lookup<Key, Environment, Error, Value>` has been changed to `Lookup<Key, Value, Error = never, Environment = never>`

## Related

- Related Issue #
- Closes #

### CODE REVIEW

**Comment by KhraksMamtsov** [comment]
I don't understand why there are not only my changes in the commit

**Comment by mikearnaldi** [comment]
can you please rebase your branch on `next-minor` ? so that the other commits disappear

**Comment by KhraksMamtsov** [comment]
Sorry, but I don't understand how to do this (
There are no branches in my fork that are in the main repository

Maybe there is another solution? I used to just do PR to the main branch and it worked)

**Comment by mikearnaldi** [comment]
`git rebase -i origin/next-minor` or a different upstream if you named the remote differently

**Comment by KhraksMamtsov** [comment]
https://github.com/Effect-TS/effect/pull/2239

**Comment by KhraksMamtsov** [comment]
Hope this https://github.com/Effect-TS/effect/pull/2239 is right approach

**Pull request closed without merging**
