### PR TITLE
feat(Stream): implement Success, Error, Context type accessors

### PR DESCRIPTION
**Pull request by dilame**
## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Related

- Related Issue #
- Closes #

### CODE REVIEW

**Comment by mikearnaldi** [comment]
This should be rebased to include only the single change and not unrelated commits

**Comment by dilame** [comment]
I already did it several times, and it was ok, but the unrelated commits are appearing again and again after some time.
I will rebase one more time now

**Comment by dilame** [comment]
@mikearnaldi i rebased all my PRs

**Comment by mikearnaldi** [comment]
> I already did it several times, and it was ok, but the unrelated commits are appearing again and again after some time. I will rebase one more time now

cc @tim-smart looks like the bot doesn't rebase properly

**Pull request merged**
