### PR TITLE
play with Effect.Service

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by mikearnaldi** [comment]
Screenshot 2024-09-28 at 11 11 35

The reason for the type level dance in the original implementation is because otherwise auto-complete doesn't work

**Comment by mikearnaldi** [comment]
I think I prefer https://github.com/Effect-TS/effect/pull/3690 as this has the issue of not creating an opaque type for the service (and also doesn't make the tag a layer)

**Comment by tim-smart** [comment]
> type-level still has some issues

Maybe a chainable api would be better. 

```ts
class Users extends Effect.Service.scoped<Users>()(
  Effect.gen(function*() {
    // ...
  }),
  { dependencies: [] }
) {}
```

Hmm, not sure I like it.

**Comment by mikearnaldi** [comment]
> > type-level still has some issues
> 
> Maybe a chainable api would be better.
> 
> ```ts
> class Users extends Effect.Service.scoped<Users>()(
>   Effect.gen(function*() {
>     // ...
>   }),
>   { dependencies: [] }
> ) {}
> ```
> 
> Hmm, not sure I like it.

not sure, wondering if we can find a way to not have the excessive keys show in auto-complete, similar issue is:

Screenshot 2024-10-01 at 10 05 19

**Comment by mikearnaldi** [comment]
also I don't quite like `.layer` and `.layerWithoutDependencies`, we should probably standardise on `.Default | .DefaultWithoutDependencies`

**Pull request merged**
