### PR TITLE
add Readable & Subscribable modules

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by jessekelly881** [comment]
`Subscribable.unwrap :: Effect<Subscribable> -> Subscribable`?

**Comment by mikearnaldi** [comment]
Maybe a `Readable` with the `get` and `Subscribable` as a sub-type of `Readable`?

**Comment by tim-smart** [comment]
I was thinking about it, but Readable just seems like `Effect<A>`.

**Comment by mikearnaldi** [comment]
> I was thinking about it, but Readable just seems like `Effect<A>`.

if we want Ref & co to implement it it needs to be a `{ get }`

**Comment by jessekelly881** [comment]
Effect could probably implement Readable as well. `get get(){ return this }` (so could Option and Either but there are probably circularity issues)

**Comment by tim-smart** [comment]
> Effect could probably implement Readable as well. `get get(){ return this }` (same with Option and Either). I wonder if there might not be circularity issues though..

Hmm doesn't make too much sense to me, as Readable / Ref is supposed to represent a handle to some mutable value. Effect represents a computation.

**Pull request merged**
