### PR TITLE
`Secret` generalization

### PR DESCRIPTION
**Pull request by KhraksMamtsov**
## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
I wanted to protect any type of data from accidental logging - for example coordinates, amounts of money ...

The `Secret` has been generalized to work with any data
Added the necessary schemas `SecretFromString` and `SecretFromSelf`
Now the `Secret` implements `Pipeable`
The tests were placed in a separate module

I'm not sure if it was possible to do this with backward compatibility support

## Related

- Related Issue #
- Closes #

### CODE REVIEW

**Comment by mikearnaldi** [comment]
In theory this could be done in a non-breaking manner by adding a `Redacted` module and by making `Secret = Redacted<string>`

**Comment by tim-smart** [comment]
Or maybe we could make it `Secret<A = string>`?

**Comment by KhraksMamtsov** [comment]
> Or maybe we could make it `Secret<A = string>`?

@qlonik , it is impossible to provide the same semantics for `unsafeWipe`, and `isSecret` will now `is Secret<unknown>`

I think I'll implement @mikearnaldi idea with the second module, and mark the `Secret` with @deprecated. 

Are there any additional ideas? maybe some other naming?

**Comment by tim-smart** [comment]
Closing in favour of the Redacted PR.

**Pull request closed without merging**
