### PR TITLE
FiberRefs perf work

### PR DESCRIPTION
**Pull request by mikearnaldi**

### CODE REVIEW

**Comment by mikearnaldi** [comment]
@tim-smart from preliminary testing by @schickling this seems to have a large (positive) impact, not sure which change specifically my guess is more aggressive caching

**Comment by tim-smart** [comment]
Yes I think the caching would have the largest impact.

Will measure the changes separately later to see how they affect performance.

**Comment by mikearnaldi** [comment]
waiting for green light from @schickling to merge this

**Review by tim-smart — APPROVED** [review]

**Comment by schickling** [comment]
image

**Pull request merged**
