### PR TITLE
List.Map should correctly provide index parameter to mapper function

### PR DESCRIPTION
**Pull request by leonitousconforti**
## Pull Requests

We welcome contributions via pull requests! Here are some guidelines to help you get started:

1. Fork the repository and clone it to your local machine.
2. Create a new branch for your changes: `git checkout -b my-new-feature`
3. Install dependencies: `pnpm install` (`pnpm@8.x`)
4. Make your changes and add tests if applicable.
5. Run the tests: `pnpm test`
6. Generate the documentation if applicable: `pnpm docgen`
7. Create a changeset for your changes: before committing your changes, create a changeset to document the modifications. This helps in tracking and communicating the changes effectively. To create a changeset, run the following command: `pnpm changeset`.
8. Commit your changes: after creating the changeset, commit your changes with a descriptive commit message: `git commit -am 'Add some feature'`.
9. Push your changes to your fork: `git push origin my-new-feature`.
10. Open a pull request against our `main` branch.

### Pull Request Guidelines

- Please make sure your changes are consistent with the project's existing style and conventions.
- Please write clear commit messages and include a summary of your changes in the pull request description.
- Please make sure all tests pass and add new tests as necessary.
- If your change requires documentation, please update the relevant documentation.
- Please be patient! We will do our best to review your pull request as soon as possible.

### CODE REVIEW

**Comment by leonitousconforti** [comment]
couldn't run docgen:

```
@leonitousconforti ➜ /workspaces/effect (mapWithIndex) $ pnpm docgen

> effect@2.0.0-next.52 docgen /workspaces/effect
> docgen

[INFO] Configuration file found
[INFO] Reading modules...
[INFO] 144 module(s) found
[INFO] Parsing modules...
Error: The following error(s) occurred while parsing the TypeScript source files:
Missing documentation in src/GlobalValue.ts module
```

But I don't think that error is from me

**Comment by gcanti** [comment]
> docgen had an error

fixed https://github.com/Effect-TS/effect/pull/1587

**Comment by gcanti** [comment]
@leonitousconforti 

- if you rebase or merge `main` you should be able to run `pnpm docgen` without errors
- you can fix the CI failure by running `pnpm lint-fix`

**Comment by tim-smart** [comment]
Hi, thanks for PR :) I'm just going to quickly take over so we can get this in todays release.

**Pull request merged**
