### PR TITLE
feat: add `mapNonEmpty` to `Chunk` and `List`

### PR DESCRIPTION
**Pull request by FedericoBiccheddu**

### CODE REVIEW

**Comment by tim-smart** [comment]
I think updating the `map` api to preserve the type is a better option. Do you want to give this a shot?

**Comment by FedericoBiccheddu** [comment]
> I think updating the `map` api to preserve the type is a better option. Do you want to give this a shot?

Sure. I tried to have the api coherent with other modules.

**Comment by tim-smart** [comment]
Here is some inspiration:

```diff
diff --git a/src/List.ts b/src/List.ts
index 05d9386fc..ea252a421 100644
--- a/src/List.ts
+++ b/src/List.ts
@@ -79,6 +79,24 @@ export interface Cons<A> extends Iterable<A>, Equal.Equal, Pipeable, Inspectable
   readonly tail: List<A>
 }

+/**
+ * @since 2.0.0
+ * @category models
+ */
+export declare namespace List {
+  /**
+   * @since 2.0.0
+   * @category models
+   */
+  export type Infer<T extends List<any>> = T extends List<infer A> ? A : never
+
+  /**
+   * @since 2.0.0
+   * @category models
+   */
+  export type With<T extends List<any>, A> = T extends Nil<infer _> ? List<A> : Cons<A>
+}
+
 /**
  * Converts the specified `List` to a `ReadonlyArray`.
  *
@@ -717,8 +735,8 @@ export const last = <A>(self: List<A>): Option.Option<A> => isNil(self) ? Option
  * @category combinators
  */
 export const map: {
-  <A, B>(f: (a: A) => B): (self: List<A>) => List<B>
-  <A, B>(self: List<A>, f: (a: A) => B): List<B>
+  <T extends List<any>, B>(f: (a: List.Infer<T>) => B): (self: T) => List.With<T, B>
+  <T extends List<any>, B>(self: T, f: (a: List.Infer<T>) => B): List.With<T, B>
 } = dual(2, <A, B>(self: List<A>, f: (a: A) => B): List<B> => {
   if (isNil(self)) {
     return self as unknown as List<B>
```

**Comment by gcanti** [comment]
For now, I'm going to merge this PR since the new APIs are consistent with the existing ones in other modules. I've opened a new issue to track the proposal for unification (https://github.com/Effect-TS/effect/issues/1520).

**Pull request merged**
