### PR TITLE
change Effect type parameters order

### PR DESCRIPTION
**Pull request by gcanti**
## Type

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

### CODE REVIEW

**Comment by bwbuchanan** [comment]
Should this have been a major release item? It breaks essentially all code that explicitly references the `Effect` type. In one of my codebases, I have more than 1500 type signatures that now need to be updated.

Also, the documentation at https://effect.website/docs/essentials/effect-type still references the old type parameter order.

**Comment by mikearnaldi** [comment]
> Should this have been a major release item? It breaks essentially all code that explicitly references the `Effect` type. In one of my codebases, I have more than 1500 type signatures that now need to be updated.
> 
> Also, the documentation at https://effect.website/docs/essentials/effect-type still references the old type parameter order.

Up until version 3.0 minors are considering breaking, that's the release policy we set for to exit from `next` targets.

There is a codemod available to help you migrate the code: `npx @effect/codemod minor-2.3 src/**/*.ts`.

You may want to join discord to be up to date and follow the release notes

**Comment by bwbuchanan** [comment]
@mikearnaldi Thanks for the clarification and the pointer to the codemod, which handled about 99.5% of the transformation.

**Comment by mikearnaldi** [comment]
> @mikearnaldi Thanks for the clarification and the pointer to the codemod, which handled about 99.5% of the transformation.

Nice! thanks for letting us know it worked :)

**Pull request merged**
