### PR TITLE
add RequestResolver.fromEffectTagged

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by mikearnaldi** [comment]
Not sure it works type wise, the request type could be a union of different requests and a generic error can't be used to complete all the potential requests

**Comment by tim-smart** [comment]
Yes in that case in wouldn't make sense, the thought was to have an api for easily lifting an `Effect<never, E, Iterable<A>>` into a batched resolver.

**Comment by mikearnaldi** [comment]
> Yes in that case it wouldn't make sense, the thought was to have an api for easily lifting an `Effect<never, E, Iterable<A>>` into a batched resolver.

but how do you prevent usage with multiple request types? maybe some kind of check in the param

**Comment by tim-smart** [comment]
This could be cool:

```ts
const Resolver = Resolver.fromEffectTags<UserById | AllUserIds>()({
  UserById: reqs => Effect.forEach(reqs, getUser, { concurrency: "unbounded" }),
  AllUserIds: reqs => Effect.forEach(reqs, () => allUserIds),
})
```

**Comment by mikearnaldi** [comment]
> This could be cool:
> 
> ```ts
> const UserResolver = Resolver.fromEffectTags<UserById | AllUserIds>()({
>   UserById: reqs => usersById(reqs.map(_ => _.id)),
>   AllUserIds: reqs => Effect.forEach(reqs, () => allUserIds),
> })
> ```

It should be possible, requests have a tag

**Pull request merged**
