### PR TITLE
remove no longer necessary './internal/timeout'

### PR DESCRIPTION
**Pull request by ethanniser**
## Type

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

oven-sh/bun#3333 was closed back in october to have behavior 1-1 with node, so this `isBun` check is no longer necessary

## Related

- Related Issue #
- Closes #

### CODE REVIEW

**Comment by ethanniser** [comment]
adding a changeset now sorry

**Comment by fubhy** [comment]
We can imho remove the entire internal timeout.ts file again and use setTimeout directly.

**Comment by tim-smart** [comment]
I feel like you missed updating the `clock` module?

**Comment by ethanniser** [comment]
yea my bad, I only searched for `./internal/timeout` but that was clearly not enough sorry
fixing now

**Comment by ethanniser** [comment]
tsc ran fine so I think I got them all

again sorry about the oversight

**Comment by tim-smart** [comment]
> tsc ran fine so I think I got them all
> 
> again sorry about the oversight

No problem, thanks for the contribution :)

**Pull request merged**
