### PR TITLE
fix: tap and andThen fallthrough function

### PR DESCRIPTION
**Pull request by patroza**
fixes for example:
```ts
declare const foo: (x: number) => Effect.Effect<void>;
Effect.succeed(true).pipe(Effect.tap(foo)); // no error
Effect.succeed(true).pipe(Effect.tap(x => foo(x))); // error
```

### CODE REVIEW

**Comment by mikearnaldi** [comment]
Mmm what about Effects that are functions? Like the proxy ones from the new tag

**Comment by patroza** [comment]
> Mmm what about Effects that are functions? Like the proxy ones from the new tag

What about them? It they match the supported function signature, then they’re golden. Otherwise they are I believe rightfully rejected.

**Comment by mikearnaldi** [comment]
I think if an arg is both a function and an effect we have to force `() =>` because the impl will take a choice, either there is an `isFunction` or `isEffect`. Quite a conondrum...

**Comment by patroza** [comment]
> I think if an arg is both a function and an effect we have to force `() =>` because the impl will take a choice, either there is an `isFunction` or `isEffect`. Quite a conondrum...

I see, seems like a related topic, how is it affected by this change?

**Comment by mikearnaldi** [comment]
It's not affected but related, with the intro of effect.tag we can't
basically distinguish functions from effects, it is an issue for tacit
usage

**Comment by patroza** [comment]
> It's not affected but related, with the intro of effect.tag we can't basically distinguish functions from effects, it is an issue for tacit usage

alright, would at least like to get the bug fix merged so that users stop getting bit by it.
In the meantime we can look into it.
From my gut feeling though; isn’t the proxy hiding the internals on access? On phone. Would need some test cases I guess

**Review by tim-smart — APPROVED** [review]

**Comment by tim-smart** [comment]
I think there are a few other places where we assume an Effect isn't a function, will need to hunt them down.

**Comment by patroza** [comment]
> It's not affected but related, with the intro of effect.tag we can't basically distinguish functions from effects, it is an issue for tacit usage

I see now yes, that's certainly 'fun' :D

**Comment by patroza** [comment]
> It's not affected but related, with the intro of effect.tag we can't basically distinguish functions from effects, it is an issue for tacit usage

How about https://github.com/Effect-TS/effect/pull/2266/files#diff-1eaca66f74be66210f25595750619630e4d14443b5ddaa1f2f8a265256432778R5292

**Pull request merged**
