### PR TITLE
Changed `Stream.groupByKey` JSDoc category from `utils` to `grouping`

### PR DESCRIPTION
**Pull request by dilame**

### CODE REVIEW

**Comment by gcanti** [comment]
What about `grouped` and `groupedWithin`?

**Comment by dilame** [comment]
Do you think it is also `grouping`? I was based on assumption that `grouping` is the category that works with `GroupBy` module, and `grouped*` family doesn't do it

**Comment by gcanti** [comment]
not sure, groupAdjacentBy is also tagged as a grouping function

**Comment by dilame** [comment]
FMPOV it is more of a `buffering` based on time than grouping, but changed it also

**Pull request merged**
