### PR TITLE
Change `Effect/Stream.acquireRelease` function signatures in favor of using an object with named functions

### PR DESCRIPTION
**Pull request by KhraksMamtsov**
## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Using an object improves readability. 
Brings the signature of a function to the same pattern as used in `Effect.tryPromise({ try, catch })`

```ts
// before: 
 const acquireDBConnection = Effect.acquireRelease(
   Effect.sync(() => createConnection('mysql://...')),
   (connection) => Effect.sync(() => connection.end(() => {})),
 )

// after:
 const acquireDBConnection = Effect.acquireRelease({
   acquire: Effect.sync(() => createConnection('mysql://...')),
   release: (connection) => Effect.sync(() => connection.end(() => {})),
 })
```

## Related

- Related Issue #
- Closes #

### CODE REVIEW

**Comment by KhraksMamtsov** [comment]
I've developed codemod also. so if this PR has value, I'll do a PR in codemode if needed.

**Comment by mikearnaldi** [comment]
It used to be like that but unfortunately inference is problematic, given that `release` depends on the type of `acquire`, maybe we can get around it with the new `NoInfer`? Cc @tim-smart @IMax153 @gcanti

**Comment by KhraksMamtsov** [comment]
I've used custom `NoInfer<>`, or you mean ts-5.4 intrinsic?

**Comment by mikearnaldi** [comment]
> I've used custom `NoInfer<>`, or you mean ts-5.4 intrinsic?

Custom one, was wondering though if `NoInfer` is the reason we could not make it work before

**Comment by KhraksMamtsov** [comment]
I think it still has problems( I had to rewrite https://github.com/Effect-TS/effect/pull/2214/files#diff-4ba919f54512656f08fc7467137253953332e37248856cd471f5995f9f5616edR3048 because of inferring problems
I've tried 5.4.0-beta and it doesn't work as I expected( but it is beta

**Comment by mikearnaldi** [comment]
Well if it doesn't work it doesn't work

**Comment by KhraksMamtsov** [comment]
please close the PR if you think it is necessary

**Comment by mikearnaldi** [comment]
I will check it better when I am back Tuesday, I hoped it was working

**Comment by mikearnaldi** [comment]
MMM this seems to be a TS bug imho, if we change the `acquire` signature to be a function like `() => ...` it works fine

**Comment by mikearnaldi** [comment]
I mean next major

**Pull request closed without merging**
