### PR TITLE
Use Nix to manage all dependencies in CI

### PR DESCRIPTION
**Pull request by IMax153**
Converts our CI environment to utilize the Nix devShell environment for running everything.

The only wrinkle that I have locally at the moment is that when I attempt to spin up my devShell, I get:

```
error: builder for '/nix/store/lq7mg8cziypsydsygx3j83ip83kqns9f-playwright-browsers-1.40.0.drv' failed with exit code 1;
       last 10 log lines:
       >     at TLSSocket._finishInit (node:_tls_wrap:1017:8)
       >     at ssl.onhandshakedone (node:_tls_wrap:803:12) {
       >   code: 'SELF_SIGNED_CERT_IN_CHAIN'
       > }
       > Failed to install browsers
       > Error: Failed to download Chromium 120.0.6099.28 (playwright build v1091), caused by
       > Error: Download failure, code=1
       >     at ChildProcess.<anonymous> (/nix/store/awkhn463308xl3vdp6h754ffk67fpmww-playwright-driver-1.40.0/package/lib/server/registry/browserFetcher.js:91:16)
       >     at ChildProcess.emit (node:events:517:28)
       >     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
       For full logs, run 'nix log /nix/store/lq7mg8cziypsydsygx3j83ip83kqns9f-playwright-browsers-1.40.0.drv'.
```

Can one of you folks check and see if you get the same error locally?

### CODE REVIEW

**Comment by fubhy** [comment]
> Can one of you folks check and see if you get the same error locally?

Works here:

Screenshot 2023-12-04 at 22 46 35

**Comment by IMax153** [comment]
@fubhy - great! That means it's probably just an issue with my local Nix configuration, which I suspected anyways. Thank you for double checking!

@fubhy @mikearnaldi - once you folks give the 👍 to this, I think we can merge it.

**Comment by mikearnaldi** [comment]
Unfortunately it is broken on mine. Same error as Max.

```
michaelarnaldi@MAC-8938DF effect % 
direnv: loading ~/repositories/effect/.envrc                                                                                                
direnv: using flake
error (ignored): error: SQLite database '/Users/michaelarnaldi/.cache/nix/eval-cache-v5/2b753f9a50cd615e963d357a851fd1d3cc720bd524c1c7adc99714deee82e95b.sqlite' is busy
[1/0/1 copied (0.0/146.9 MiB), 0.0/23.8 MiB DL] fetching source from https://cache.nixos.orgdirenv: ([/Users/michaelarnaldi/.nix-profile/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
error: builder for '/nix/store/lq7mg8cziypsydsygx3j83ip83kqns9f-playwright-browsers-1.40.0.drv' failed with exit code 1;
       last 10 log lines:
       >     at TLSSocket._finishInit (node:_tls_wrap:1017:8)
       >     at ssl.onhandshakedone (node:_tls_wrap:803:12) {
       >   code: 'SELF_SIGNED_CERT_IN_CHAIN'
       > }
       > Failed to install browsers
       > Error: Failed to download Chromium 120.0.6099.28 (playwright build v1091), caused by
       > Error: Download failure, code=1
       >     at ChildProcess.<anonymous> (/nix/store/awkhn463308xl3vdp6h754ffk67fpmww-playwright-driver-1.40.0/package/lib/server/registry/browserFetcher.js:91:16)
       >     at ChildProcess.emit (node:events:517:28)
       >     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
       For full logs, run 'nix log /nix/store/lq7mg8cziypsydsygx3j83ip83kqns9f-playwright-browsers-1.40.0.drv'.
error: 1 dependencies of derivation '/nix/store/9ls3jr4dr8npz5z6va7idzlrqks94434-nix-shell-env.drv' failed to build
direnv: export ~XPC_SERVICE_NAME
```

**Comment by fubhy** [comment]
@IMax153 Let me know if you want to debug together to figure out why it works on mine and not on yours.

**Comment by IMax153** [comment]
@mikearnaldi @fubhy - do you folks use `nix-darwin` to manage your machines?

**Pull request merged**
