### PR TITLE
Swap Either type params

### PR DESCRIPTION
**Pull request by mikearnaldi**
Swap type params of Either from `Either<E, A>` to `Either<R, L = never>`.

Along the same line of the other changes this allows to shorten the most common types such as:

```ts
import { Either } from "effect";

const right: Either.Either<string> = Either.right("ok");
```

While it was confusing to use `Either<A, E>` I don't find it particularly confusing to use `Either<R, L>`, the type reads like "it's either a right or a left"

### CODE REVIEW

**Comment by ethanniser** [comment]
**I think this a good change to keep it in line with all of the other changed types**

But I am curious why the decision to only modify the type parameter order, and not the runtime semantics?

Surely the function named `Either.right` would result in a `Either` with the type of the right?

```ts
const right: Either.Either<string, never> = Either.right("ok"); // right = left
const left: Either.Either<never, number> = Either.left(5); // left = right
```

because `Either` is "just a tagged union" there shouldn't be any reason that 'right' belongs to the first type parameter anymore than left

making them match just feels nicer?

of course it makes it a bit of a bigger migration, but its already a breaking change

**Comment by mikearnaldi** [comment]
> **I think this a good change to keep it in line with all of the other changed types**
> 
> But I am curious why the decision to only modify the type parameter order, and not the runtime semantics?
> 
> Surely the function named `Either.right` would result in a `Either` with the type of the right?
> 
> ```ts
> const right: Either.Either<string, never> = Either.right("ok"); // right = left
> const left: Either.Either<never, number> = Either.left(5); // left = right
> ```
> 
> because `Either` is "just a tagged union" there shouldn't be any reason that 'right' belongs to the first type parameter any more than left
> 
> making them match just feels nicer?
> 
> of course it makes it a bit of a bigger migration, but its already a breaking change

Users complained that "right" feels like "success" and "left" doesn't

**Comment by patroza** [comment]
gj for swapping to more semantic L and R.
there's still the obvious swapping in the generics: Right is on the Left and Left is on the Right.
but that's alright

**Review by fubhy — APPROVED** [review]

**Comment by jessekelly881** [comment]
+1 for changing the name of `left`, `right`. Rust uses Ok() and Err(). Maybe that's a good alternative name.

**Comment by mikearnaldi** [comment]
> +1 for changing the name of `left`, `right`. Rust uses Ok() and Err(). Maybe those are good alternative names.

Ok / Err would suggest primary usage as a Result, Either is used in Effect as a disjoined union given that for results we use Exit

**Comment by jessekelly881** [comment]
Hmm. Yeah, I get your point. Although there are instances where it's implicitly treated as a Result. E.g. Effect.flatMap(either).

**Comment by mikearnaldi** [comment]
> Hmm. Yeah, I get your point. Although there are instances where it's implicitly treated as a Result. E.g. Effect.flatMap(either).

That's for convenience nothing more

**Comment by datner** [comment]
I think it should be noted in the docs, otherwise we will have fp devotees knocking at the door

**Comment by mikearnaldi** [comment]
> I think it should be noted in the docs, otherwise we will have fp devotees knocking at the door

they can keep believing their cult and use fp-ts v2 :) jokes aside, yes everything needs to be documented

**Comment by samhh** [comment]
I'm late to the party on this, but does this not make any prospective migration from fp-ts more difficult? If so, is it really worth it?

**Comment by mikearnaldi** [comment]
> I'm late to the party on this, but does this not make any prospective migration from fp-ts more difficult? If so, is it really worth it?

We are not optimizing for fp-ts migration, we are optimizing for newcomers and effect users.o

The migration from fp-ts is a much larger topic, in fp-ts Either was used as a Result, in Effect results are expressed as Exit and also 90% of the direct Either usages should probably instead be straight Effect usages.

**Pull request merged**
