### PR TITLE
expose Layer MemoMap apis

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by tim-smart** [comment]
Will need to add ref counting to prevent cases where Layers could be released too early.

**Comment by mikearnaldi** [comment]
Was about to say, that part is already needed

**Comment by mikearnaldi** [comment]
Something is off here. The following:

```ts
const fromLayer = <RIn, E, ROut>(
  evaluate: Layer.Layer<RIn, E, ROut>
): Layer.Layer<RIn, E, ROut> => {
  const suspend = Object.create(proto)
  suspend._tag = OpCodes.OP_SUSPEND
  suspend.evaluate = () => evaluate
  return suspend
}
```

doesn't quite make sense, evaluate is not lazy so this should be a no-op. I see though that removing it makes the newly implemented tests fail which is strange

**Comment by mikearnaldi** [comment]
Even replacing `fromLayer` with suspend makes the test fail. 100% something is broken

**Comment by tim-smart** [comment]
We can remove it and use suspend instead.

We can't use fromEffectContect directly in fromEffect, as that doesn't hit the memomap.

**Comment by mikearnaldi** [comment]
Using suspend doesn't work

**Comment by mikearnaldi** [comment]
also fromEffectContext should hit the memo map, every layer should

**Comment by tim-smart** [comment]
Ah no we can't, as then we lose referential equality...

**Comment by tim-smart** [comment]
> also fromEffectContext should hit the memo map, every layer should

https://github.com/Effect-TS/effect/blob/af9fd6d79a234760e7a5d84778142cf216a8b5b4/src/internal/layer.ts#L380

AFAIK, that is the final point of construction, which can't use the memo map otherwise it would create a busy loop.

**Comment by mikearnaldi** [comment]
```ts
/**
 * Constructs a layer from the specified effect, which must return one or more
 * services.
 *
 * @since 2.0.0
 * @category constructors
 */
export const effectContext: <R, E, A>(effect: Effect.Effect<R, E, Context.Context<A>>) => Layer<R, E, A> =
  internal.fromEffectContext
```

**Comment by mikearnaldi** [comment]
would be "ok" if internal but this just allows users to create layers that are never memoized

**Comment by tim-smart** [comment]
I don't think effectContext needs it, because there is no Scope and Context is immutable?

**Comment by tim-smart** [comment]
Ah yeah, there could be side effects though.

**Comment by mikearnaldi** [comment]
Precisely, well we could wrap the public facing version with fromLayer

**Comment by tim-smart** [comment]
Fixed :)

**Pull request merged**
