### PR TITLE
WIP: added Subscribable.fromStream

### PR DESCRIPTION
**Pull request by jessekelly881**
## Type

- [x] Feature

## Description

Adds Subscribable.fromStream. The idea is that the Subscribable keeps track of the last value of the Stream(or the defaultValue if the stream hasn't yet emitted a value). I honestly doubt that this is the best implementation for this fn though.. :(

### CODE REVIEW

**Comment by tim-smart** [comment]
What's the use case for this?

**Comment by jessekelly881** [comment]
I'm using this for periodically polling an api w/ `Option.none` as the default.

**Comment by jessekelly881** [comment]
I'm using this for periodically polling an api w/ `Option.none` as the default.

**Comment by tim-smart** [comment]
I think in that case using a SubscriptionRef is a better fit.

**Pull request closed without merging**
