### PR TITLE
effect: add Stream.filterMapEffectOption function

### LINKED ISSUE #3018: Stream.filterMapEffect but accepting Effect<Option<A>> instead of Option<Effect<A>>
### What is the problem this feature would solve?

`Stream.filterMapEffect` is unique to the rest of the `Stream.*Effect` functions: it expects an effect wrapped in another data structure instead of an effect _containing_ a data structure: `(a: A) => Option<Effect<B>>`

or in other words, if you want to `filterMapEffect` you can't filter map based on an effect value, but instead you can choose whether to return an effect or not

Let's say we want to map a stream of numbers into their square roots:

```typescript
declare const sqrt = (number: number) => Effect.Effect<Option<number>>;

const numbers = Stream.fromIterable([-1,2,3])

// What we can do right now
const squareRoots_ = numbers.pipe(
  Stream.mapEffect(number => sqrt(number)),
  Stream.filterMap(opt => opt)
);

// With this filterMapEffectX (name tbd):
const squareRoots = numbers.pipe(
  Stream.filterMapEffectX(number => sqrt(number))
)
```

### What is the feature you are proposing to solve the problem?

it seems counter intuitive that this is the signature IMO, and I know that we probably can't break this API as Effect 3 is stable -- so we'll have to think of a different way to call it.

This is obviously can be done in userland as I mentioned previously, which is how I implemented it on my projects:

```typescript
import { Function, Stream, Effect, Option } from 'effect';

export const filterMapEffect = Function.dual<
  <A, A2, E2, R2>(
    fn: (a: A) => Effect.Effect<Option.Option<A2>, E2, R2>,
  ) => <E, R>(
    stream: Stream.Stream<A, E, R>,
  ) => Stream.Stream<A2, E2 | E, R2 | R>,
  <A, E, R, A2, E2, R2>(
    stream: Stream.Stream<A, E, R>,
    fn: (a: A) => Effect.Effect<Option.Option<A2>, E2, R2>,
  ) => Stream.Stream<A2, E2 | E, R2 | R>
>(2, (stream, fn) =>
  Stream.filterMap(Stream.mapEffect(stream, fn), Function.identity),
);
```

### What alternatives have you considered?

The alternative is to simply keep that a userland implementation. But I think this API makes sense in the "standard library".

### PR DESCRIPTION
**Pull request by Schniz**
## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adds a `Stream.mapEffectFilter` function that maps items of a stream effectfully,
and then filters them.

## Related

- Closes #3018

### CODE REVIEW

**Comment by mikearnaldi** [comment]
cc @tim-smart @IMax153 what do we think of the name?

**Comment by IMax153** [comment]
> cc @tim-smart @IMax153 what do we think of the name?

I'll be honest, I'm not a fan of this name. I find it confusing given there's also filterMapEffect. 

That being said I don't have a good alternative at the moment 😬.

**Comment by Schniz** [comment]
There are couple of alternatives I generated with AI: all feel as wrong IMO

https://sdk.vercel.ai/s/7HAZozu43jqI

**Comment by tim-smart** [comment]
Can we overload the predicate return type of `filterMapEffect` to be `Option<Effect> | Effect<Option>` I wonder.

The only case that could cause issues is if you return `Option<Option>`.

**Comment by mikearnaldi** [comment]
> Can we overload the predicate return type of `filterMapEffect` to be `Option<Effect> | Effect<Option>` I wonder.
> 
> The only case that could cause issues is if you return `Option<Option>`.

given Option is an Effect a union such as this would not be possible

**Comment by tim-smart** [comment]
`Stream.filterMapEffectOption`?

**Comment by mikearnaldi** [comment]
> `Stream.filterMapEffectOption`?

let's go for this and re-think in 4.0 if we can have a single function

**Comment by IMax153** [comment]
Yea I second Tim's suggestion - `Stream.filterMapEffectOption` is good for now 👍

**Comment by Schniz** [comment]
<picture data-single-emoji=":done:" title=":done:">:done:</picture> <picture data-single-emoji=":effect-ts:" title=":effect-ts:">:effect-ts:</picture>

**Comment by mikearnaldi** [comment]
apologies @Schniz I merged by mistake, needs to be re-opened given the lack of a changeset

**Pull request merged**
