### PR TITLE
feat: add `withDefaultConstructor`

### PR DESCRIPTION
**Pull request by patroza**
#1997

- the defaults are carried with on the fields so that they can be picked and transferred to build other classes

```ts
    it("supports defaults", () => {
      class A extends S.Class<A>("A")({
        a: S.string,
        b: S.number.pipe(S.withDefaultConstructor(() => 1)),
        c: S.number.pipe(S.withDefaultConstructor(() => 1), S.fromKey("d"))
      }) {}
      expect({ ...new A({ a: "abc" }) }).toStrictEqual({ a: "abc", b: 1, c: 1 })
      expect({ ...new A({ a: "abc", b: 2, c: 2 }) }).toStrictEqual({ a: "abc", b: 2, c: 2 })
    })
```
this is where defaults really matter 90% of my usecases.

### CODE REVIEW

**Comment by steffanek** [comment]
@patroza would be nice to have 2 types of default:
- One that can be overwritten by the caller, like you did,
- but also another one that can't be overwritten.
Would that make sense?

**Comment by patroza** [comment]
> @patroza would be nice to have 2 types of default:
> 
> * One that can be overwritten by the caller, like you did,
> * but also another one that can't be overwritten.
> 
> Would that make sense?

If you want a constant just put it on the class as a prop?

**Comment by steffanek** [comment]
> > @patroza would be nice to have 2 types of default:
> > 
> > * One that can be overwritten by the caller, like you did,
> > * but also another one that can't be overwritten.
> > 
> > Would that make sense?
> 
> If you want a constant just put it on the class as a prop?

Not really, cuz the constant would be available for the entire class and I only need it for the construction.

**Comment by patroza** [comment]
> Not really, cuz the constant would be available for the entire class and I only need it for the construction.

I'm very confused. maybe you can paint the use case with example code.

**Comment by steffanek** [comment]
> > Not really, cuz the constant would be available for the entire class and I only need it for the construction.
> 
> I'm very confused. maybe you can paint the use case with example code.

I like to have an attribute to represent the Event, (ex: "PersonCreated" for a DomainStartEvent). It's only needed for the construction, but I don't want the caller to be able to change it.

**Comment by patroza** [comment]
@steffanek use `TaggedClass`

**Comment by steffanek** [comment]
> @steffanek use `TaggedClass` ?

nah I don't want the event to be an object by itself. I come up with a different domain modeling approach.

**Comment by gcanti** [comment]
Closing in favour of https://github.com/Effect-TS/effect/pull/2634

**Pull request closed without merging**
