### PR TITLE
add Stream.asyncPush api

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by mikearnaldi** [comment]
Same as in the other PR, dropping elements by default is not a good choice

**Comment by mikearnaldi** [comment]
Options could be `{ strategy: "unbounded" }` by default and potentially accept `{ strategy: "dropping" / "sliding", size: 100 }`

The nice aspect about this is that assuming we don't support backpressure we can guarantee sync push, which would be faster than the plain async way

**Comment by tim-smart** [comment]
> Same as in the other PR, dropping elements by default is not a good choice

Have changed it to "unbounded" by default.

**Pull request merged**
