### PR TITLE
fix: Schema.omit on a union

### PR DESCRIPTION
**Pull request by sukovanej**
## Type

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

I included a test example how we discovered the problem. 

Result without the change:

```
  Object {
    "_id": "Either",
    "_tag": "Right",
    "right": Object {
-     "b": Object {
-       "_id": "Option",
-       "_tag": "Some",
-       "value": "a",
-     },
+     "b": "a",
    },
  }
```

### CODE REVIEW

**Comment by sukovanej** [comment]
@gcanti could you please take a look? 

I'm aware this is not precise from the type stand-point as the type-level `Omit` is not distributive. Still, this feels like the correct and expected behaviour in the runtime so I'd definitely vote for not disabling this case.

**Comment by gcanti** [comment]
Sorry for responding only now (I've been super busy with the latest release). Looks like it's working as intended though, since `schema2: S.Schema<{}, {}, never>`.

**Comment by sukovanej** [comment]
> Sorry for responding only now (I've been super busy with the latest release)
I was checking the minor branch periodically and saw you producing commits like crazy. So no worry, I completely understood what's happening 😄 

> Looks like it's working as intended though, since schema2: S.Schema<{}, {}, never>.
I meant it in a way that `Omit` not distributing on a union is causing confusion a lot (based on stackoverflow and github  discussions)

**Comment by gcanti** [comment]
Yes, I understand that it can be a source of confusion, but the principle is to keep the runtime and type-level as aligned as possible. So, either we maintain the current signature of `omit` and its corresponding implementation (which I prefer), or if we change the implementation, the signature also needs to be changed.

**Comment by mikearnaldi** [comment]
I think we should keep alignment and eventually do a distributiveOmit version that can distribute

**Comment by sukovanej** [comment]
Hey, that makes sense to me. Thank you. Closing.

**Pull request closed without merging**
