### PR TITLE
use Proxy for TaggedEnum constructors

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by mikearnaldi** [comment]
We may want to change:

```ts
const Result = Data.taggedEnum<ResultDefinition>()
const Success = Result.Success
const Failure = Result.Failure
```

to:

```ts
const { Success, Failure } = Data.taggedEnum<ResultDefinition>()
```

as a convention

**Comment by tim-smart** [comment]
Sounds good. I added back support for the previous syntax - but I feel like the api is too complex with both.

**Comment by tim-smart** [comment]
> Sounds good. I added back support for the previous syntax - but I feel like the api is too complex with both.

Yeah if we push for destructuring as the recommended usage pattern, I think dropping the function constructors is reasonable.

**Comment by mikearnaldi** [comment]
> > Sounds good. I added back support for the previous syntax - but I feel like the api is too complex with both.
> 
> Yeah if we push for destructuring as the recommended usage pattern, I think dropping the function constructors is reasonable.

I kind of agree yeah

**Pull request merged**
