### PR TITLE
add support for deno in test suite

### PR DESCRIPTION
**Pull request by tim-smart**
- [x] docgen fix for markdown-toc dependency
- [x] add `deno task test` to CI
- [ ] generate Deno import map

### CODE REVIEW

**Comment by pixeleet** [comment]
@tim-smart With latest deno 1.38 tests seems to work with the `unstable-byonm` flag enabled

image

**Comment by pixeleet** [comment]
Alternatively just doing `deno --unstable-byonm task test` does the same trick

**Comment by tim-smart** [comment]
> Alternatively just doing `deno --unstable-byonm task test` does the same trick

Well that certainly makes it easier :)

**Comment by ryanleecode** [comment]
So for deno we can just use `platform-node` and it will work?

**Comment by pixeleet** [comment]
that is what you're doing effectively when doing `import { ... } from
"npm:effect"`

Ryan Lee ***@***.***> ezt írta (időpont: 2024. márc. 23.,
Szo, 6:47):

**Pull request merged**
