### PR TITLE
remove generator boxing by using a Proxy

### PR DESCRIPTION
**Pull request by tim-smart**

### CODE REVIEW

**Comment by mikearnaldi** [comment]
Why would a proxy provide less boxing? Usually proxy is slower

**Comment by tim-smart** [comment]
> Why would a proxy provide less boxing? Usually proxy is slower

By boxing, I mean returning a boxed type from the iterator (YieldWrap).

Perf wise, this performs better on jsc (bun) but worse on v8 (node) - so not sure it is worth it.

The only benefit is future proofing ourselves, if ts ever decides to let you define the behaviour of plain `yield`.

Node:
Screenshot 2024-04-29 at 9 46 03 AM

Bun:
Screenshot 2024-04-29 at 9 46 55 AM

**Comment by tim-smart** [comment]
Bun:
image

Node:
image

**Comment by mikearnaldi** [comment]
Not sure I understand how this prevents a loop though

**Comment by tim-smart** [comment]
> Not sure I understand how this prevents a loop though

The iterators return a copy of the original Effect but with an empty Symbol.iterator.

**Comment by tim-smart** [comment]
It is good to know it is possible though, if the day ever comes.

**Pull request closed without merging**
